Revert "printk: help pr_debug and pr_devel to optimize out arguments"
../include/linux/printk.h:113:1:
   error: expected expression before 'do'
../drivers/misc/qcom/qdsp6v2/dts_eagle/dts_eagle_drv.h:21:6: note: in expansion of macro 'no_printk'
../drivers/misc/qcom/qdsp6v2/dts_eagle/dts_eagle_drv.c:150:2: note: in expansion of macro 'dts_eagle_drv_dbg_msg'
...

This reverts commit e72d8e7e772cdafe76d24ee2b23e5d434971a928.